version: '3'

volumes:
  postgres_volume:

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "${RMQ_PORT_MANAGEMENT}:15672"
      - "5672:5672"
    hostname: rabbitmq
    restart: always
    environment:
            - "RABBITMQ_DEFAULT_USER=${RMQ_USER}"
            - "RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}"
            - "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    
  migrator:
    build:
      context: .
      dockerfile: db-migration/migrations.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    environment:
      DB_HOST: pg
      RMQ_HOST: rabbitmq
      PG_DSN: "postgres://${PG_USER}:${PG_PASSWORD}@pg:5432/${PG_DATABASE_NAME}?sslmode=disable"
      RMQ_DSN: "amqp://${RMQ_USER}:${RMQ_PASSWORD}@rabbitmq:5672/"
      GRPC_HOST: "${GRPC_HOST}"
      GRPC_PORT: "${GRPC_PORT}"
    depends_on:
      - pg
      - rabbitmq