version: '3'

volumes:
  postgres_volume:

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "${RMQ_PORT}:15672"
      - "5672:5672"
    hostname: rabbitmq
    restart: always
    environment:
            - "RABBITMQ_DEFAULT_USER=${RMQ_USER}"
            - "RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}"
            - "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: db-migration/migrations.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg